const names = require("./moduleapp")
const sayhi = require("./3app")
const app6 = require("./6app")
require("./app7")
console.log(names)
sayhi(names.john)
sayhi(names.peter)
sayhi("yanis")
console.log(app6.singelPerson.age)
